name: Release

on:
    push:
        tags:
            - v*
    workflow_dispatch:

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      platform: linux
                    - os: windows-latest
                      platform: windows

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Run Electron Builder
              if: ${{ matrix.platform != 'mac' }}
              run: |
                  pnpm electron-builder --${{ matrix.platform }} --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Upload each file in dist/ to the release
              shell: bash
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  TAG_NAME=$(git describe --tags --abbrev=0)
                    for file in dist/*; do
                    if [ -f "$file" ]; then
                        echo "Uploading $file to release $TAG_NAME..."
                        gh release upload "$TAG_NAME" "$file" --clobber
                    else
                        echo "Skipping $file (not a file)"
                    fi
                    done

        
